In [9]:
"""
数学函数 包含了大量各种数学运算的函数，三角函数，算数函数，复数处理等
三角函数 
    sin()正弦
    cos()余弦
    tanc()正切

反三角函数 
    arcsin()反正弦
    arcoss()反余弦 
    arctan()反正切

反转计算成角度degrees(sin,cos,tan) 返回 角度值

"""
import numpy as np
a = np.array([30,45,60])
print(a)


#弧度 = np.pi /180
sin_sum = np.sin(a * np.pi / 180)#正弦
cos_sum = np.cos(a * np.pi / 180)#余弦

#打印 正弦、余弦、正切
tan_sum = np.cos(a * np.pi / 180)#正切
print(sin_sum)
print(cos_sum)
print(tan_sum)

sin_arg = np.arcsin(sin_sum) #反正弦
cos_arg = np.arcsin(cos_sum)#反余弦
tan_arg = np.arcsin(tan_sum)#反正切
print(sin_arg)
print(cos_arg)
print(tan_arg)


#反转正弦角度，反转余弦角度,反转正切角度
print(np.degrees(sin_arg))
print(np.degrees(cos_arg))
print(np.degrees(tan_arg))

[30 45 60]
[0.5        0.70710678 0.8660254 ]
[0.8660254  0.70710678 0.5       ]
[0.8660254  0.70710678 0.5       ]
[0.52359878 0.78539816 1.04719755]
[1.04719755 0.78539816 0.52359878]
[1.04719755 0.78539816 0.52359878]
[30. 45. 60.]
[60. 45. 30.]
[60. 45. 30.]


In [14]:
"""
舍入函数
around函数 四舍五入值 1.数组 2.舍入的小数位：默认0
floor函数 向下取整数
ceil函数  向上取整数
"""

import numpy as np
a = np.around([20.3,30.62,59.222]) #四舍五入
print(a)
print(type(a))
b = np.floor([20.3,30.62,59.222]) #向下取整数
print(b)
c = np.ceil([20.3,30.62,59.222]) #向上取整数
print(c)

[20. 31. 59.]
<class 'numpy.ndarray'>
[20. 30. 59.]
[21. 31. 60.]


In [29]:
"""
算法函数 数组的加减乘除，数组必须具有相同的形状，符合广播规则
add() + 加
subtract() -减
multiply() *乘
divide() /c除
reciprocal() 倒数，元素的倒数1/4 倒数4/1
power() 1.底数 2.幂次方
mod() 两数组余数

"""
import numpy as np
a = np.arange(9,dtype = np.float64).reshape(3,3)
b = np.array([10,10,10])
# print(np.add(a,b)) #加法
# print(np.subtract(a,b)) #减法
# print(np.multiply(a,b)) #乘法
# print(np.divide(a,b)) #除法

##幂次方
c = np.array([10,100,1000])
print(np.power(c,2)) #幂次方
d = np.array([1,2,3])
print(np.power(c,d))

#倒数
e = np.array([0.25,1.33,1,100])
print(np.reciprocal(e))

#两数组余数
num1 = np.array([10,20,30])
num2 = np.array([3,5,7])
print(np.mod(num1,num2))

[    100   10000 1000000]
[        10      10000 1000000000]
[4.        0.7518797 1.        0.01     ]
[1 0 2]
