In [8]:
import numpy as np
print(np.__version__)

1.15.1


In [20]:
import numpy as np
print(np.__version__)

1.15.1


In [9]:
"""
数组（Arrays）三维
特点：1.array()把python的类型转换正np的nd array
     2.转换过数组的始终数据不变
函数：1.最大值max（）
2.最小值min（）
3.形状shape属性 输出结果:(6,)一维6长度
索引和切片
1.通过元素的下标位
2.通过元素的start：stop
排序
1.sort
2.sorted
获取列的值
1.[1,1]返回一个一维数组
2.[1,np.newaxis,1] 保留数据原来的位置返回数组

"""
import numpy as np
c = np.array([[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]])
# print(c)
# print(c.shape)
# # print(c.max(),c.min())
# print(c[:][:][0])
print(c[:][0][1])
print(c[0][:][1])

[4 5 6]


In [12]:
"""
参数 元组 shape
创建数组0
填充的多维数组 zeros（）
默认类型：float
dtype 可以设置元素类型 np.uint8 整数
astype 重置数组元素类型
创建数组1填充形状的多维数组ones
"""
import  numpy  as np
z = np.zeros((3,3),dtype=np.uint8) #全部为0，类型是整型
print(z)
f = z.astype(np.float64)#类型是浮点型
print(f)
one = np.ones((3,3),dtype=np.unit8) #全部为1，类型是整型
print(one)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
"查看文件位置"
import os 
print(os.path.abspath('.'))


D:\study


In [17]:
"""
repeat() 重复元素 1.元素 2,.重复次数
"""
import numpy as np

f = np.repeat((3,4,5),3)
print(f)

[3 3 3 4 4 4 5 5 5]


In [19]:
"""
广播(Broadcasting)
广播是一种强大的机制，它允许numpy在执行算术运算时使用
不同形状的数组
s.shape = b.shape 形状相同

"""
import numpy as np
#形状相同
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a*b
print(c)

#形状不同
num1 = np.array([[1,2,3],[10,10,10],[20,20,20],[30,30,30]])
num2 = np.array([1,2,3])
num3 = num1 + num2
print(num3)

[ 10  40  90 160]
[[ 2  4  6]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
