In [1]:
"""
统计函数 从数组中快速查询最大、最小、百分位标准差
amin()参数：axis 1行比、0比例
amax()
ptp()最大值-最小值的差
percentile() 度量，百分比1.数组2.半分比 0-100 3.axis
median() 算数平均值
std()标准差 sqrt(mean(x-x.mean())**2)
    标准差是一组数组的平均值分散程度的一种度量
var()方差mean((x-x.mean())**2)
    平均数之差的平方的平均数
加权平均数average（）各个数值乘以相应的权数，
     然后总求和得到总体值，再除以总数
     参数：weights：权重系数（可选参数，默认1）
"""
import numpy as np
a = np.array([[3,7,5],[8,2,3],[2,4,9]])
print(a)
print(np.amax(a,axis=1)) #行最大值   行1
print(np.amax(a,axis=0)) #列最大值   列是0
print("默认最大值",np.amax(a)) #默认最大值
print("行最小值",np.amax(a,axis=1)) #行最小值
print("列最小值",np.amax(a,axis=0)) #列最小值

#百分值 50% 的分位数，a排序后的中位数
print(np.percentile(a,50)) #百分值
print(np.percentile(a,50,axis=1)) #行百分值
print(np.percentile(a,50,axis=0)) #列百分值
print(np.percentile(a,50,axis=0,keepdims=True))
#百分值 维持数组形状保持不变



[[3 7 5]
 [8 2 3]
 [2 4 9]]
[7 8 9]
[8 7 9]
默认最大值 9
行最小值 [7 8 9]
列最小值 [8 7 9]
4.0
[5. 3. 4.]
[3. 4. 5.]
[[3. 4. 5.]]


In [3]:

import numpy as np
a = np.array([95,85,75,65,55,45])
b = np.array([73,72,71,69,68,67])
print('A组的方差为:',np.var(a))
print('B组的方差为:',np.var(b))

c = np.array([80,90,95])
d = np.array([95,90,80])
e = [0.2,0.3,0.5]
print(np.weights(c,weights(e)))
print(np.weights(d,weights(e)))


A组的方差为: 291.6666666666667
B组的方差为: 4.666666666666667


AttributeError: module 'numpy' has no attribute 'weights'

In [1]:
import numpy as np


#中位数
print("中位数",np.median(a)) #中位数
# print("行中位数",np.median(a,axis=1)) #"行中位数
print("列中位数",np.median(a,axis=0)) #"列中位数


#平均数
# print('平均数',np.mean(a,axis=0))
# print('列方',np.mean(a,axis=1))
# print('')


#加权平均数
# b = np.array([20,30,40])
# print(b)
# print('加权',np.average(b,weights=[1,2,3]))
# print('平均数',np.mean(b))


NameError: name 'a' is not defined