In [11]:
"""
bool_ 布尔型数据类型（True 或者False）

int_ 默认的整数类型(类似与C语言中的龙，int32或int64)

intc 和C语言的int 类型一样，一般是int32 或int64

intp 用于索引的整型(类似与C的ssize_t,通常int32 或int64)

float_ float64类型的简写

float16/32/64 半精度浮点数：1个符号位，5个指数位，10个尾数位
              单精度浮点数：1个符号位，8个指数位，23个位数位
        双精度浮点数，包括：1个符号位，11个指位数，52个位数位

complex_ 复数类型，与complex128类型相同

complex64/128 复数，表示双32位浮点数（实数部分和虚数部分）
              复数，表示双64位浮点数（实数部分和虚数部分）
              
coplex_ 复数类型，与complex128类型相同

string 表示字节串类型，也就是bytes 类型

int8/32/64  代表与1字节相同的8位整数
            代表与2字节相同的16位整数
            代表与4字节相同的32位整数
            代表与8字节相同的64位整数
            
            
                代表1字节（8位）无符号整型
unit8/16/32/64  代表与2字节相同的16位整型
                代表与4字节相同的32位整型
                代表与8字节相同的64位整型
"""

'\nbool_ 布尔型数据类型（True 或者False）\n\nint_ 默认的整数类型(类似与C语言中的龙，int32或int64)\n\nintc 和C语言的int 类型一样，一般是int32 或int64\n\nintp 用于索引的整型(类似与C的ssize_t,通常int32 或int64)\n\nfloat_ float64类型的简写\n\nfloat16/32/64 半精度浮点数：1个符号位，5个指数位，10个尾数位\n\n\ncoplex_ 复数类型，与complex128类型相同\n\nstring 表示字节串类型，也就是bytes 类型\n\n\n'

In [12]:
import numpy as np
#把数组中的类型转换为浮点型
#法1
a = np.array([1,2,3,4])
b = a.astype(dtype='float_')
print(b)
#法2
a1 = np.array([1,2,3,4],dtype=np.float64)
print(a1)

#布尔
c = np.array([0,1,2,3,4],dtype = np.bool_)
print(c)

#字符串
str1 = np.array([0,1,2,3,3],dtype = np.str)
str2 = np.array([0,1,2,3,4],dtype = np.string_)
print(str1,str2)
str3 = np.array(['我们',1,2,3,4,5,6,88],dtype= np.str_)
print(str3)

[1. 2. 3. 4.]
[1. 2. 3. 4.]
[False  True  True  True  True]
['0' '1' '2' '3' '3'] [b'0' b'1' b'2' b'3' b'4']
['我们' '1' '2' '3' '4' '5' '6' '88']


In [33]:
"""
定义结构化数据

b 代表布尔型
c 浮点型
S，a 字符串（S）与 字符串(a)
i 带符号整型
m 时间间隔
U Unicode
u 无符号整型
M  datatime （日期时间）
V 原始数据（void）
f 浮点型
O Python对象

"""

'\n定义结构化数据\n\nb 代表布尔型\nc 浮点型\nS，a 字符串（S）与 字符串(a)\ni 带符号整型\nm 时间间隔\nU Unicode\nu 无符号整型\nM  datatime （日期时间）\nV 原始数据（void）\nf 浮点型\nO Python对象\n\n'

In [34]:
#结构化数据类型
import  numpy as np
dt  = np.dtype([('age','U1')]) #数据类型
print(dt)
stu = np.array([("我们"),(128)],dtype = dt)
print(stu,stu.dtype)
print(stu['age'])

[('age', '<U1')]
[('我',) ('1',)] [('age', '<U1')]
['我' '1']


In [35]:
"""
三个特征：姓名 年龄 工资

str 字段 name
    字段 age
    字段 salary

"""
import numpy as np
teacher = np.dtype([('name',np.str_,3),('age','i1'),('salary','f4')])
a = np.array([('zxl',18,234.456),
              ('rxr',12,7866.80)], dtype = teacher)
print(a)
print(a['name'])
print(a['age'])
print(a['salary']

'\n三个特征：姓名 年龄 工资\nstr 字段 name\nint 字段 age\nfloat 字段 salary\n'

In [40]:
#操作文件
# np.loadtxt()  shift+tab键

np.loadtxt(fname,:#指定文件名或字符串。支持压缩文件，包括gz、bz格式
           dtype=<class 'float'>,  #数据类型 默认float。
           comments='#',#字符串或字符串组成的列表，表示注释字符集开始的标志，默认#
           delimiter=None, #字符串。分隔符
           converters=None, #字典
           skiprows=0,#跳过特定列的数据转换为字典中对应的函数的浮点型数据。例如将空值转换为0，默认为空
           usecols=None, #元组。用来指定要读取数据的列。第一列为0，例如（1,3,5）默认为空
           unpack=False,#布尔型。 指定是否转置数组，如果为真则转置，默认为False
           ndmin=0, #整数型。指定返回的数组至少包含特定维度的数组。值域0、1、2，默认为0
           encoding='bytes' #编码，确认文件是gbk还是utf-8格式

In [61]:
import numpy as np

data = np.loadtxt('data1.txt')
print(data)
data = np.loadtxt('data1.txt',dtype='int_')#读取数字文本信息
data1 = np.loadtxt('文字.txt',encoding = 'utf-8',dtype='str_') #读取字符串
print(data1)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]]
我们今天很开心
